package com.mycompany.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerDetailsAllPropertiesEquals(CustomerDetails expected, CustomerDetails actual) {
        assertCustomerDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerDetailsAllUpdatablePropertiesEquals(CustomerDetails expected, CustomerDetails actual) {
        assertCustomerDetailsUpdatableFieldsEquals(expected, actual);
        assertCustomerDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerDetailsAutoGeneratedPropertiesEquals(CustomerDetails expected, CustomerDetails actual) {
        assertThat(expected)
            .as("Verify CustomerDetails auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerDetailsUpdatableFieldsEquals(CustomerDetails expected, CustomerDetails actual) {
        assertThat(expected)
            .as("Verify CustomerDetails relevant properties")
            .satisfies(e -> assertThat(e.getGender()).as("check gender").isEqualTo(actual.getGender()))
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()))
            .satisfies(e -> assertThat(e.getAddressLine1()).as("check addressLine1").isEqualTo(actual.getAddressLine1()))
            .satisfies(e -> assertThat(e.getAddressLine2()).as("check addressLine2").isEqualTo(actual.getAddressLine2()))
            .satisfies(e -> assertThat(e.getCity()).as("check city").isEqualTo(actual.getCity()))
            .satisfies(e -> assertThat(e.getCountry()).as("check country").isEqualTo(actual.getCountry()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerDetailsUpdatableRelationshipsEquals(CustomerDetails expected, CustomerDetails actual) {}
}
